version: '3.7'
networks:
  inside:
    driver: bridge
  traefik-net:
    external: true

services:
  persona-ui:
    container_name: karim_persona_ui
    build: .
    volumes:
      - ./build:/ui/build
    environment:
      - PUBLIC_URL=/cherry-bomb/
    networks:
      - inside
      - traefik-net

  nginx:
    image: nginx
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./build:/frontend/public:ro
    depends_on:
        - persona-ui
    ports:
      - 8071:80
    networks:
      - inside
      - traefik-net

    ################################################################
    # Define the following labels for each additional service
    # in docker-compose
    ################################################################# 

    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network

      # tell Traefik which middlewares we want to use on this container
      - "traefik.http.routers.karim-router.entrypoints=websecure"
      - "traefik.http.routers.karim-router.rule=PathPrefix(`/cherry-bomb`)"
      - "traefik.http.routers.karim-router.tls=true"
      - traefik.http.routers.karim-router.middlewares=gzip

      # 2) Define and identify a new prefix middleware:
      # 2.1) Replace <YOUR_MIDDLEWARE_NAME> with an arbitrary string of your choice.
      #      If this middleware matches <YOUR_PREFIX> it will strip this prefix from
      #      the url and store it in a X-Forwarded-Prefix header.
      # 2.2) Replace <YOUR_ENDPOINT> with the string you've defined in (1.2)
      - "traefik.http.middlewares.karim_middleware_ui.stripprefix.prefixes=/cherry-bomb"

      # 3) Apply the above middleware to the previously defined router.
      # 3.1) Replace <YOUR_ROUTER> with the string you've defined in (1.1)
      # 3.2) Replace <YOUR_MIDDLEWARE_NAME> with the string you've defined in (2.1)
      - "traefik.http.routers.karim-router.middlewares=karim_middleware_ui@docker"

      # 4) Configure on which port your service is running.
      # 4.1) Replace <YOUR_SERVICE_NAME> with a string of your choice.
      # 4.2) Replace <YOUR_PORT> with the port that your web service is running on.
      - traefik.http.services.persona_ui.loadbalancer.server.port=80
